# Generated by Django 2.2.4 on 2019-09-08 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hint', models.CharField(max_length=100)),
                ('keyword', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tresure.Difficulty')),
                ('quizzes', models.ManyToManyField(to='tresure.Quiz')),
            ],
        ),
        migrations.AddField(
            model_name='difficulty',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tresure.Goal'),
        ),
        migrations.AddField(
            model_name='difficulty',
            name='quizzes',
            field=models.ManyToManyField(to='tresure.Quiz'),
        ),
    ]
