version: 2.1

executors:
  default:
    working_directory: ~/repo
    docker:
      - image: circleci/python:3.6.1

jobs:
  build:
    executor: default

    steps:
      - checkout
      -run:
          name: Install Submodule 
          command: git submodule init && git submodule update

      - run:
          name: Update pip
          command: sudo pip3 install --upgrade pip

      - run:
          name: Install dependencies
          command: sudo pip3 install Django pycodestyle --progress-bar off

      - run:
          name: Lint by pycodestyle
          command: pycodestyle --exclude=migrations,settings.py oursite

      - run:
          name: Run tests
          command: cd oursite && python3 manage.py test

      - store_artifacts:
          path: test-reports
          destination: test-reports
